/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.FrontendBuscaminas.JframeBuscaminas;

import Backend.BackendBuscaMinas.ControladorPartida.ControladorPartida;
import Backend.BackendBuscaMinas.componentesTablero.Tablero;
import Backend.BackendBuscaMinas.Temporizador.TemporizadorBuscaminas;
import Backend.BackendBuscaMinas.componentesTablero.Casilla;
import Backend.Jugador.Jugador;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author kenny
 */
public class VentanaJuegoBuscaminas extends javax.swing.JFrame {

    private final TemporizadorBuscaminas temporizador;
    private final Jugador jugador;
    private final Tablero tablero;
    private JButton[][] botonesCasillas;
    private boolean primerClickUsuario = false;
    private int contadorBanderasMina = 0;
    
    /**
     * Creates new form VentanaJuegoBuscaminas
     */
    public VentanaJuegoBuscaminas(Jugador jugador, Tablero tablero) {
        initComponents();
        this.setTitle("Minas");
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.temporizador = new TemporizadorBuscaminas();
        this.jugador = jugador;
        this.tablero = tablero;
        actualizarLabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneLTablero = new javax.swing.JPanel();
        PanelTemporizador = new javax.swing.JPanel();
        panelTemporizador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelTiempo = new javax.swing.JPanel();
        labelInicio = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labeltiempo = new javax.swing.JLabel();
        PanelDatosJugador = new javax.swing.JPanel();
        botonMenuInicial = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        labelNombreTitulo = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        labelTituloMinas = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        minasRestantes = new javax.swing.JLabel();
        scrollTamañoTabnlero = new javax.swing.JScrollBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        PaneLTablero.setBackground(new java.awt.Color(204, 204, 204));
        PaneLTablero.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout PaneLTableroLayout = new javax.swing.GroupLayout(PaneLTablero);
        PaneLTablero.setLayout(PaneLTableroLayout);
        PaneLTableroLayout.setHorizontalGroup(
            PaneLTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        PaneLTableroLayout.setVerticalGroup(
            PaneLTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        PanelTemporizador.setBackground(new java.awt.Color(153, 255, 153));
        PanelTemporizador.setForeground(new java.awt.Color(0, 204, 204));

        panelTemporizador.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TEMPORIZADOR: ");

        javax.swing.GroupLayout panelTemporizadorLayout = new javax.swing.GroupLayout(panelTemporizador);
        panelTemporizador.setLayout(panelTemporizadorLayout);
        panelTemporizadorLayout.setHorizontalGroup(
            panelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
        );
        panelTemporizadorLayout.setVerticalGroup(
            panelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
        );

        panelTiempo.setBackground(new java.awt.Color(102, 153, 255));

        labelInicio.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        labelInicio.setForeground(new java.awt.Color(0, 0, 0));
        labelInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelTiempoLayout = new javax.swing.GroupLayout(panelTiempo);
        panelTiempo.setLayout(panelTiempoLayout);
        panelTiempoLayout.setHorizontalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTiempoLayout.setVerticalGroup(
            panelTiempoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        labeltiempo.setFont(new java.awt.Font("Yrsa SemiBold", 0, 36)); // NOI18N
        labeltiempo.setForeground(new java.awt.Color(0, 0, 0));
        labeltiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labeltiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labeltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout PanelTemporizadorLayout = new javax.swing.GroupLayout(PanelTemporizador);
        PanelTemporizador.setLayout(PanelTemporizadorLayout);
        PanelTemporizadorLayout.setHorizontalGroup(
            PanelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTiempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelTemporizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTemporizadorLayout.setVerticalGroup(
            PanelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTemporizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelTiempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        PanelDatosJugador.setBackground(new java.awt.Color(102, 204, 255));
        PanelDatosJugador.setForeground(new java.awt.Color(255, 204, 204));

        botonMenuInicial.setBackground(new java.awt.Color(255, 51, 51));
        botonMenuInicial.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        botonMenuInicial.setForeground(new java.awt.Color(0, 0, 0));
        botonMenuInicial.setText("Salir");
        botonMenuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuInicialActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jLabel2.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));

        labelNombreTitulo.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelNombreTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNombreTitulo.setText("Partida de: ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombreTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 204, 255));

        labelNombre.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));
        labelNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(153, 153, 255));

        labelTituloMinas.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelTituloMinas.setForeground(new java.awt.Color(0, 0, 0));
        labelTituloMinas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloMinas.setText("Minas restantes:  ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloMinas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTituloMinas, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(153, 153, 255));

        minasRestantes.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        minasRestantes.setForeground(new java.awt.Color(0, 0, 0));
        minasRestantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minasRestantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(minasRestantes, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout PanelDatosJugadorLayout = new javax.swing.GroupLayout(PanelDatosJugador);
        PanelDatosJugador.setLayout(PanelDatosJugadorLayout);
        PanelDatosJugadorLayout.setHorizontalGroup(
            PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMenuInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelDatosJugadorLayout.setVerticalGroup(
            PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosJugadorLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(botonMenuInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PaneLTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTemporizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PanelDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollTamañoTabnlero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PaneLTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollTamañoTabnlero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuInicialActionPerformed
        // TODO add your handling code here:
        temporizador.finalizarTemporizador();
        JOptionPane.showMessageDialog(this, "Has abandonado la partida-");
        
        VentanaBuscaminas ventanaJuego = new VentanaBuscaminas();
        ventanaJuego.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_botonMenuInicialActionPerformed

    /**
     * Metodo encargado de ir actualizando los labels, como el tiempo desde la clase 
     * temporizador se usa un hilo.
     * 
     */
    private void actualizarLabels(){
        temporizador.setActualizadorDeTiempo((String tiempo) -> {
           
        labelInicio.setText("Tiempo: ");
        labeltiempo.setText(tiempo);
    });
        
        labelInicio.setText("Tiempo: ");
         labeltiempo.setText("00:00");
        
        
         String cantidadMinas = Integer.toString(tablero.getCantidadMinas());
         String minasMax = Integer.toString(tablero.getMinasMax());
         
         labelNombre.setText(jugador.getNombreJugador());
         minasRestantes.setText(cantidadMinas + "/ " + minasMax);
    }
    
    /**
     * Metodo encargado de generar el tablero, desde la clase tablero se manda a llamar
     * el metodo de mostrar el tablero vacio sin minas 
     */
    public void generarTablero() {
        tablero.mostrarTablero();
        int filas = tablero.getCantidadFilasTablero();
        int columnas = tablero.getCantidadColumnasTablero();

        botonesCasillas = new JButton[filas][columnas];
        
        diseñoTablero(filas, columnas);

        for (int i = 0; i < filas; i++) {
            for (int j = 0; j < columnas; j++) {
                colocarBotonesEnTablero(i, j);
            }
        }

        PaneLTablero.revalidate();
        PaneLTablero.repaint();
    }
    
    private void diseñoTablero(int filas, int columnas){
        PaneLTablero.removeAll();
        PaneLTablero.setLayout(new GridLayout(filas, columnas));
        PaneLTablero.setPreferredSize(new Dimension(1117, 570));
        
    }

    private void colocarBotonesEnTablero(int i, int j) {
        
        JButton botonCasillas = new JButton();
        botonCasillas.setPreferredSize(new Dimension(40, 40));
        botonCasillas.setFocusPainted(false);
        botonCasillas.setBackground(Color.white);
        botonCasillas.setFont(new Font("Arial", Font.BOLD, 14));

        botonesCasillas[i][j] = botonCasillas;

        botonCasillas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                Casilla casillaActual = tablero.getCasilla(i, j);

                if (e.getButton() == java.awt.event.MouseEvent.BUTTON1) {
                    manejarClickIzquierdo(i, j, botonCasillas, casillaActual);
                } else if (e.getButton() == java.awt.event.MouseEvent.BUTTON3) {
                    manejarClickDerecho(botonCasillas, casillaActual);
                }
            }
        });

        PaneLTablero.add(botonCasillas);
    }
    
    private void manejarClickIzquierdo(int i, int j, JButton boton, Casilla casilla) {
        if (casilla.estaMarcada()) return;

        temporizador.iniciarTemporizador();

        if (casilla.casillaEstaRevelada())
            return;

        if (!primerClickUsuario) {
            tablero.generarCasillas(i, j);
            tablero.generarEfectoDomino(i, j);
            primerClickUsuario = true;
        }

        if (casilla.esCasillaMinada()) {
            casilla.revelarCasilla();
            actualizarBoton(boton, casilla);
            temporizador.finalizarTemporizador();
            revelarTodasLasMinas();
            JOptionPane.showMessageDialog(null, "💥 ¡Has perdido! Tocaste una mina.");
            regresarVentana();
            return;
        }

        casilla.revelarCasilla();
        actualizarBoton(boton, casilla);

        if (casilla.getCantidadMinasAdyacentes() == 0 && !casilla.esCasillaMinada()) {
            tablero.generarEfectoDomino(i, j);
        }

        for (int fila = 0; fila < tablero.getCantidadFilasTablero(); fila++) {
            for (int columna = 0; columna < tablero.getCantidadColumnasTablero(); columna++) {
                Casilla c = tablero.getCasilla(fila, columna);
                if (c.casillaEstaRevelada()) {
                    actualizarBoton(botonesCasillas[fila][columna], c);
                }
            }
        }

        verificarVictoria();
    }

    
   private void manejarClickDerecho(JButton boton, Casilla casilla) {
        if (!casilla.casillaEstaRevelada()) {
            casilla.alternarMarcado();  

            if (casilla.estaMarcada()) {  
                if (casilla.esCasillaMinada()) {  
                    contadorBanderasMina++; 
                }

                ImageIcon banderaIcono = new ImageIcon(getClass().getResource("/recursos/buscaminasBanderaBoton.png"));
                Image imagenRedimensionada = banderaIcono.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
                boton.setIcon(new ImageIcon(imagenRedimensionada));
                boton.setText(""); 
            } else { 
                if (casilla.esCasillaMinada()) { 
                    contadorBanderasMina--; 
                }

                boton.setIcon(null);  
            }

            actualizarLabelMinas(); 
        }
    }



    private void actualizarLabelMinas() {
     

        int minasTotales = tablero.getMinasMax();
        int minasRestantesMinima = Math.max(minasTotales - contadorBanderasMina, 0);

        minasRestantes.setText(minasRestantesMinima + " / " + minasTotales);
    }



    
    private void actualizarBoton(JButton boton, Casilla casillaActual) {
        if (casillaActual.casillaEstaRevelada()) {
            boton.setBackground(Color.LIGHT_GRAY);
            boton.setFont(new Font("Arial", Font.BOLD, 18));

            if (casillaActual.esCasillaMinada()) {
                ImageIcon iconoMina = new ImageIcon(getClass().getResource("/recursos/bombaImagen.png"));
                Image imagenRedimensionada = iconoMina.getImage().getScaledInstance(30, 30, Image.SCALE_SMOOTH);
                boton.setIcon(new ImageIcon(imagenRedimensionada));
                boton.setText("");
            } else {
                int minasAdyacentes = casillaActual.getCantidadMinasAdyacentes();

                if (minasAdyacentes > 0) {
                    boton.setText(String.valueOf(minasAdyacentes));
                    boton.setIcon(null);
                    switch (minasAdyacentes) {
                        case 1 -> boton.setForeground(Color.BLUE);
                        case 2 -> boton.setForeground(new Color(0, 128, 0));
                        case 3 -> boton.setForeground(Color.RED);
                        case 4 -> boton.setForeground(new Color(0, 0, 128));
                        case 5 -> boton.setForeground(new Color(128, 0, 0));
                        case 6 -> boton.setForeground(new Color(64, 224, 208));
                        case 7 -> boton.setForeground(Color.BLACK);
                        case 8 -> boton.setForeground(Color.GRAY);
                    }
                } else {
                    boton.setText("");
                    boton.setIcon(null);
                }
            }
        }
    }

    private void revelarTodasLasMinas() {
        for (int i = 0; i < tablero.getCantidadFilasTablero(); i++) {
            for (int j = 0; j < tablero.getCantidadColumnasTablero(); j++) {
                Casilla casilla = tablero.getCasilla(i, j);
                if (casilla.esCasillaMinada()) {
                    casilla.revelarCasilla();
                    actualizarBoton(botonesCasillas[i][j], casilla);
                }
            }
        }
    }

    private void verificarVictoria() {
        for (int i = 0; i < tablero.getCantidadFilasTablero(); i++) {
            for (int j = 0; j < tablero.getCantidadColumnasTablero(); j++) {
                Casilla casilla = tablero.getCasilla(i, j);
                if (!casilla.esCasillaMinada() && !casilla.casillaEstaRevelada()) {
                    return; 
                }
            }
        }
         temporizador.finalizarTemporizador();
         revelarTodasLasMinas(); 
        JOptionPane.showMessageDialog(null, "🎉 ¡Felicidades! Has ganado el juego.");
        regresarVentana();
        
        
    }


    private void regresarVentana(){
        VentanaBuscaminas ventana = new VentanaBuscaminas();
        
        this.setVisible(false);
        
        ventana.setVisible(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneLTablero;
    private javax.swing.JPanel PanelDatosJugador;
    private javax.swing.JPanel PanelTemporizador;
    private javax.swing.JButton botonMenuInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreTitulo;
    private javax.swing.JLabel labelTituloMinas;
    private javax.swing.JLabel labeltiempo;
    private javax.swing.JLabel minasRestantes;
    private javax.swing.JPanel panelTemporizador;
    private javax.swing.JPanel panelTiempo;
    private javax.swing.JScrollBar scrollTamañoTabnlero;
    // End of variables declaration//GEN-END:variables
}
