/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frontend.FrontendBuscaminas.JframeBuscaminas;

import Backend.BuscaMinas.Tablero.Tablero;
import Backend.BuscaMinas.Temporizador.TemporizadorBuscaminas;
import Backend.Jugador.Jugador;
import javax.swing.JFrame;

/**
 *
 * @author kenny
 */
public class VentanaJuegoBuscaminas extends javax.swing.JFrame {

    private TemporizadorBuscaminas temporizador;
    private Jugador jugador;
    private Tablero tablero;
    
    /**
     * Creates new form VentanaJuegoBuscaminas
     */
    public VentanaJuegoBuscaminas(Jugador jugador, Tablero tablero) {
        initComponents();
        this.setTitle("Minas");
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.temporizador = new TemporizadorBuscaminas();
        this.jugador = jugador;
        this.tablero = tablero;
        
        
        temporizador.setActualizadorDeTiempo((String tiempo) -> {
           
        labelInicio.setText("Tiempo en curso: ");
        labeltiempo.setText(tiempo);
    });
        
        
         String cantidadMinas = Integer.toString(tablero.getCantidadMinas());
         
         labelNombre.setText(jugador.getNombreJugador());
         minasRestantes.setText(cantidadMinas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PaneLTablero = new javax.swing.JPanel();
        PanelTemporizador = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelInicio = new javax.swing.JLabel();
        labeltiempo = new javax.swing.JLabel();
        PanelDatosJugador = new javax.swing.JPanel();
        botonMenuInicial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        labelNombreTitulo = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        minasRestantes = new javax.swing.JLabel();
        labelTituloMinas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        PaneLTablero.setBackground(new java.awt.Color(51, 51, 51));
        PaneLTablero.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout PaneLTableroLayout = new javax.swing.GroupLayout(PaneLTablero);
        PaneLTablero.setLayout(PaneLTableroLayout);
        PaneLTableroLayout.setHorizontalGroup(
            PaneLTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 914, Short.MAX_VALUE)
        );
        PaneLTableroLayout.setVerticalGroup(
            PaneLTableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        PanelTemporizador.setBackground(new java.awt.Color(102, 102, 255));
        PanelTemporizador.setForeground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("TEMPORIZADOR: ");

        labelInicio.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelInicio.setForeground(new java.awt.Color(0, 0, 0));

        labeltiempo.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labeltiempo.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelTemporizadorLayout = new javax.swing.GroupLayout(PanelTemporizador);
        PanelTemporizador.setLayout(PanelTemporizadorLayout);
        PanelTemporizadorLayout.setHorizontalGroup(
            PanelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelTemporizadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labeltiempo, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelTemporizadorLayout.setVerticalGroup(
            PanelTemporizadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTemporizadorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labeltiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        PanelDatosJugador.setBackground(new java.awt.Color(0, 204, 204));
        PanelDatosJugador.setForeground(new java.awt.Color(255, 204, 204));

        botonMenuInicial.setBackground(new java.awt.Color(153, 153, 255));
        botonMenuInicial.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        botonMenuInicial.setText("Salir");
        botonMenuInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenuInicialActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DATOS: ");

        labelNombreTitulo.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelNombreTitulo.setForeground(new java.awt.Color(0, 0, 0));
        labelNombreTitulo.setText("Partida de: ");

        labelNombre.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(0, 0, 0));

        minasRestantes.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        minasRestantes.setForeground(new java.awt.Color(0, 0, 0));

        labelTituloMinas.setFont(new java.awt.Font("Yrsa SemiBold", 0, 24)); // NOI18N
        labelTituloMinas.setForeground(new java.awt.Color(0, 0, 0));
        labelTituloMinas.setText("Minas restantes:  ");

        javax.swing.GroupLayout PanelDatosJugadorLayout = new javax.swing.GroupLayout(PanelDatosJugador);
        PanelDatosJugador.setLayout(PanelDatosJugadorLayout);
        PanelDatosJugadorLayout.setHorizontalGroup(
            PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(botonMenuInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDatosJugadorLayout.createSequentialGroup()
                .addGroup(PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelDatosJugadorLayout.createSequentialGroup()
                        .addComponent(labelNombreTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(PanelDatosJugadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(minasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTituloMinas))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PanelDatosJugadorLayout.setVerticalGroup(
            PanelDatosJugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelDatosJugadorLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombreTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(labelTituloMinas)
                .addGap(29, 29, 29)
                .addComponent(minasRestantes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonMenuInicial))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PaneLTablero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(PanelDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTemporizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PanelDatosJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(PaneLTablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonMenuInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonMenuInicialActionPerformed
        // TODO add your handling code here:
        temporizador.finalizarTemporizador();
        jugador.setTiempoBuscaminas(temporizador.obtenerSegundosTemporizador());
        VentanaBuscaminas ventanaJuego = new VentanaBuscaminas();
        ventanaJuego.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_botonMenuInicialActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaneLTablero;
    private javax.swing.JPanel PanelDatosJugador;
    private javax.swing.JPanel PanelTemporizador;
    private javax.swing.JButton botonMenuInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelInicio;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreTitulo;
    private javax.swing.JLabel labelTituloMinas;
    private javax.swing.JLabel labeltiempo;
    private javax.swing.JLabel minasRestantes;
    // End of variables declaration//GEN-END:variables
}
